ARG CLOUDNATIVEPG_VERSION

FROM ghcr.io/cloudnative-pg/postgresql:$CLOUDNATIVEPG_VERSION-standard-bookworm
USER root

ARG POSTGRES_VERSION
ARG TIMESCALE_VERSION
RUN <<EOT
  set -eux

  # Install dependencies
  apt-get update
  apt-get install -y --no-install-recommends curl

  # Add Timescale apt repo
  . /etc/os-release 2>/dev/null
  echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $VERSION_CODENAME main" >/etc/apt/sources.list.d/timescaledb.list
  curl -Lsf https://packagecloud.io/timescale/timescaledb/gpgkey | gpg --dearmor >/etc/apt/trusted.gpg.d/timescale.gpg

  # Install Timescale
  apt-get update
  apt-mark hold "postgresql-$POSTGRES_VERSION" "postgresql-client-$POSTGRES_VERSION"
  apt-get install -y --no-install-recommends \
    "timescaledb-2-loader-postgresql-$POSTGRES_VERSION=$TIMESCALE_VERSION~debian12" \
    "timescaledb-2-postgresql-$POSTGRES_VERSION=$TIMESCALE_VERSION~debian12"

  # Cleanup
  apt-get purge -y curl
  rm /etc/apt/sources.list.d/timescaledb.list /etc/apt/trusted.gpg.d/timescale.gpg
  rm -rf /var/cache/apt/*
EOT

USER 26
